algoritmo "area_e_perimetro_do_retangulo"
// Função : Calcular a área e o perímetro do retângulo
// Autor : Guilherme Gutierrez
// Data : 04/05/2020
// Seção de Declarações 
var
b,h,a,p:real
inicio
// Seção de Comandos
escreval("Digite a base do retângulo:")
leia(b)
escreval("Digite a altura do retângulo:")
leia(h)
//processamento
a<-(b*h)
p<-(b+h)*2
//resposta
escreval("A área do retângulo é:",a)
escreval("O perímetro do retângulo é:",p)
fimalgoritmo
